In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [2]:
type(arr)

numpy.ndarray

In [10]:
newarr = arr.reshape(2,-1)

In [11]:
newarr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
newarr[0,0:2]

array([1, 2])

In [14]:
newarr[0:2,1]

array([2, 5])

In [35]:
arr = np.arange(0,100,5).reshape(5,-1)
arr

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [40]:
arr[arr<10]

array([0, 5])

In [37]:
arr*2

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110],
       [120, 130, 140, 150],
       [160, 170, 180, 190]])

In [38]:
arr+5

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

In [39]:
arr/5

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [44]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [45]:
np.ones((4,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [49]:
np.random.rand(3,4)

array([[0.3263175 , 0.26980077, 0.23084814, 0.76115624],
       [0.60163359, 0.75241728, 0.6159394 , 0.59801211],
       [0.23852278, 0.36045237, 0.16370246, 0.95081838]])

In [54]:
np.random.randint(1,50,10).reshape(2,5)

array([[20, 18,  6, 20, 30],
       [21, 11, 26, 26,  2]])

In [2]:
import pandas as pd
import numpy as np

In [29]:
df = pd.DataFrame(np.arange(0,100,5).reshape(5,4),index=['r1','r2','r3','r4','r5'],columns=['c1','c2','c3','c4'])
df

c1  c2  c3  c4
r1   0   5  10  15
r2  20  25  30  35
r3  40  45  50  55
r4  60  65  70  75
r5  80  85  90  95

In [13]:
df.iloc[2]

c1    40
c2    45
c3    50
c4    55
Name: r3, dtype: int32

In [19]:
df.iloc[1:4,0:2].values

array([[20, 25],
       [40, 45],
       [60, 65]])

In [30]:
df['c1']

r1     0
r2    20
r3    40
r4    60
r5    80
Name: c1, dtype: int32

In [26]:
df.isnull().sum()

c1    0
c2    0
c3    0
c4    0
dtype: int64